--DROP TABLE IF EXISTS Audiologists_Customers;
--DROP TABLE IF EXISTS Audiologists;
CREATE TABLE IF NOT EXISTS  Audiologists(
	id bigint NOT NULL,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	CONSTRAINT PK_Audiologists PRIMARY KEY  
	(
		id ASC
	)
);

--DROP TABLE IF EXISTS Customers;
CREATE TABLE IF NOT EXISTS Customers(
	id bigint NOT NULL generated by default as identity,
	first_name varchar(50) NOT NULL,
	last_name varchar(50) NOT NULL,
	 CONSTRAINT PK_Customers PRIMARY KEY 
	(
		id ASC
	)
);


CREATE TABLE IF NOT EXISTS Audiologists_Customers(
	audiologist_id bigint NOT NULL,
	customer_id bigint NOT NULL,
	CONSTRAINT PK_Audiologists_Customers PRIMARY KEY 
	(
		audiologist_id ,
		customer_id ASC
	),
	FOREIGN KEY (audiologist_id) REFERENCES Audiologists(id),
	FOREIGN KEY (customer_id) REFERENCES Customers(id)
);

--DROP TABLE IF EXISTS Appointments;
CREATE TABLE IF NOT EXISTS  Appointments(
	id bigint NOT NULL generated by default as identity,
	customer_id bigint NOT NULL,
	audiologist_id bigint NOT NULL,
	appointment_date datetime,
	rate int,
	CONSTRAINT PK_Appointments PRIMARY KEY  
	(
		id ASC
	),
	
	FOREIGN KEY (audiologist_id) REFERENCES Audiologists(id),
	FOREIGN KEY (customer_id) REFERENCES Customers(id)
);


